---
title: "Investigation Project"
author: "CADEMI"
date: "08-09-2020"
output: html_document
---

## Abstract / Resumen.
### (Keywords).

## Methods.

Para poner a prueba las hipotesis evaluadas en este trabajo, seguimos la metodologia de Edmonson (1999). El objetivo principal fue medir seguridad psicologica en los distintos grupos, analizar y comparar las variables independientes y dependientes y comprobar su relacion entre estos *(conocimiento, comportamiento de aprendizaje, eficacia y satisfaccion de equipo)*.

Estudiamos el proceso entre los estudiantes de primer año de la carrera de *Ingenieria Comercial* del año 2020, de la *Universidad Diego Portales*. Medimos datos cuantitativos en cuanto al curso de *Fundamentos de Administracion y Negocios*. Las encuestas fueron realizadas durante un lapso de 5 meses, en distintos periodos de tiempo. Estas se realizaron a traves de los docentes del curso, los cuales nos ayudaron tambien a la confeccion de las escalas y tipos de medidas. El total de estudiantes evaluados fue de 280 aproximadamente. Desde un inicio se trabajo en grupos pequeños de 5 a 6 estudiantes. Se recopilaron 48 equipos en total, los cuales fueron evaluados en conjunto durante todo el proceso, sin ninguna modificacion o salida de alguno de estos a lo largo del periodo establecido.

Al ser un curso de primer año universitario, nadie tenia conocimientos teoricos previos en cuanto a trabajo en equipo, liderazgo o administracion. Ademas, recalcar que ninguno de los estudiantes mantenia una relacion estrecha entre sus pares o academicos de la facultad, previa la investigacion realizada. El unico medio de interaccion que tuvimos con los estudiantes a lo largo del proyecto fueron netamente las respuestas otorgadas a traves de las encuestas.

-(¿Hay alguna libreria que nos ayude a corregir las reglas gramaticales en español?)-
-P: Ni idea, en cuantos más estas acostumbrado a la literatura academica, más sueles redactar como academico.-

### Process

Analizamos detalladamente el trabajo realizado por -Amy-(Nunca el nombre) Edmonson (1999) -(siempre el año)-, durate un periodo de 5 meses. Mientras se realizaba este proceso, se efectuo tambien la recopilacion de datos a travez de las encuestas realizadas a los estudiantes.

Lo primero fue evaluar las hipotesis a comprobar dentro del proyecto (H1, H2 y H3) -(Insertar referencia a la tabla con las hipotesis)-. Para ello, se diseñaron ciertas preguntas con ayuda de los docentes, acorde a las escalas ya antes previstas -(Insertar referencia a la tabla con las preguntas)-. De esta forma, -fueron siendo entregadas a los estudiantes-(los alumnos son encuentados) a lo largo del tiempo -estimado- (establecido, no estimado: 5 meses) (t). En total se realizaron 3 periodos de encuestas que contenian este tipo de preguntas-(nose si queda claro)-.



## Results.

## Discussion.

## Conclusion.

## References.
